# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scraping(object):
    def setupUi(self, Scraping):
        Scraping.setObjectName("Scraping")
        Scraping.setEnabled(True)
        Scraping.resize(332, 470)
        Scraping.setStyleSheet("background: qlineargradient(spread:pad, x1:0.921, y1:0.961, x2:0.069, y2:0.0568182, stop:0 rgba(40, 40, 40, 255), stop:1 rgba(255, 255, 255, 255));\\n\"\"background-image:\\n\"\"    linear-gradient(\\n\n"
"      to right, \\n\n"
"      gray, black\\n\n"
"    );")
        self.centralwidget = QtWidgets.QWidget(Scraping)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 370, 131, 51))
        self.pushButton.setStyleSheet("background-color: white;\n"
"border: 3px solid black;\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"font-weight: bold;")
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 200, 191, 61))
        self.textEdit_2.setStyleSheet("background-color: white;\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(70, 300, 191, 61))
        self.textEdit_3.setStyleSheet("background-color: white;\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setEnabled(False)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 70, 201, 31))
        self.textBrowser_3.setMouseTracking(True)
        self.textBrowser_3.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setEnabled(False)
        self.textBrowser_4.setGeometry(QtCore.QRect(40, 170, 251, 31))
        self.textBrowser_4.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setEnabled(False)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 270, 311, 31))
        self.textBrowser_5.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(50, 10, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.textBrowser.setFont(font)
        self.textBrowser.setMouseTracking(True)
        self.textBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setToolTipDuration(-1)
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(200, 60, 121, 281))
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setStyleSheet("background-color:transparent ;\n"
"font-weight: bold;")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 121, 227))
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 121, 301))
        self.widget.setStyleSheet("background-color: white;\n"
"")
        self.widget.setObjectName("widget")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 121, 231))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setMouseTracking(True)
        self.textBrowser_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textBrowser_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_2.setAcceptDrops(True)
        self.textBrowser_2.setToolTipDuration(-1)
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 121, 227))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 110, 301, 61))
        self.textEdit_5.setStyleSheet("background-color: white;\n"
"border: 1px solid black;\n"
"border-radius: 10px;\n"
"font-weight:bold;")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.raise_()
        self.pushButton.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.textBrowser_5.raise_()
        self.textBrowser.raise_()
        self.toolBox.raise_()
        Scraping.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Scraping)
        self.statusbar.setObjectName("statusbar")
        Scraping.setStatusBar(self.statusbar)

        self.retranslateUi(Scraping)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Scraping)

    def retranslateUi(self, Scraping):
        _translate = QtCore.QCoreApplication.translate
        Scraping.setWindowTitle(_translate("Scraping", "MainWindow"))
        self.pushButton.setText(_translate("Scraping", "Старт"))
        self.textBrowser_3.setHtml(_translate("Scraping", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#262626;\">Введите название игры:</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Scraping", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#2c2c2c;\">Введите диапазон цен в USD:</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Scraping", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#1e1e1e;\">Лимит пустых страниц для остановки:</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Scraping", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:1pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\"> Steam Parse</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Scraping", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:1pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Dota2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">CSGO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">PUBG</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Rust</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">TeamFortress2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Unturned</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">PayDay2 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Killing Floor 2 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Don\'t Strave Together</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Z1 Battle Royale</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Black Squad</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Artifact</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Primal Carnage: Extinction </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">BLOCKPOST</span></p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Scraping", "Игры"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Scraping", "Скрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scraping = QtWidgets.QMainWindow()
    ui = Ui_Scraping()
    ui.setupUi(Scraping)
    Scraping.show()
    sys.exit(app.exec_())
